version: '3.8'

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./myapp-backend
      dockerfile: Dockerfile
    container_name: myapp-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/myappDB
      - NODE_ENV=development
    volumes:
      - ./myapp-backend:/app          # mount code để live‑reload
      - /app/node_modules             # anonymous volume giữ dependencies :contentReference[oaicite:8]{index=8}
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ./myapp-frontend
      dockerfile: Dockerfile.dev
    container_name: myapp-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - CHOKIDAR_IGNORE=node_modules,build
      - NODE_OPTIONS=--max-old-space-size=1024
    volumes:
      - ./myapp-frontend:/app         # mount code gốc để live‑reload
      - /app/node_modules             # anonymous volume giữ modules :contentReference[oaicite:9]{index=9}
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:
